### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Hylio** [nimalolikong/MDC-FIX#1]
hello there, please let me know how can i get a nas to store videos? can u buy me one?

**Comment by nimalolikong** [comment]
i don't know, maybe u can use ur four hundred thousand years' yuan paid to buy 1 hundred NAS on JD and then give me one as a gift my dear.  =^•ω•^=

**Comment by Hylio** [comment]
> i don't know, maybe u can use ur four hundred thousand years' yuan paid to buy 1 hundred NAS on JD and then give me one as a gift my dear. =^•ω•^=

sure, it's my pleasure.
